name: "Build and push Cortex container to JFrog"

on:
  push:
    branches:
      - "test"
  workflow_dispatch:

env:
  SERVER_USERNAME: ${{ secrets.JFROG_USER_PULSE8_AI }}
  SERVER_PASSWORD: ${{ secrets.JFROG_ACCESS_TOKEN_PULSE8_AI}}

permissions:
  contents: read
  id-token: write

jobs:
  buildAndPushCortex:
    runs-on: ubuntu-latest
    environment:
      name: ${{github.ref_name}}
    steps:
      - uses: actions/checkout@v4

      - name: "Build and push Cortex container"
        uses: synpulse-group/s8-actions/custom-build-push-container@main
        with:
          docker-build-context-location: .
          docker-file-path: ./Dockerfile # using our custom Dockerfile in the repo root
          jfrog-user: ${{ secrets.JFROG_USER_PULSE8_AI }} # no need to change - available in all workflows in the organisation
          jfrog-password: ${{ secrets.JFROG_ACCESS_TOKEN_PULSE8_AI }} # no need to change - available in all workflows in the organisation
          image-name-suffix: -cortex-vault-test
          target-repository: "sp-artifactory-dso-internal-pulse8-ai"


  buildAndPushQMD:
    runs-on: ubuntu-latest
    environment:
      name: ${{github.ref_name}}
    steps:
      - uses: actions/checkout@v4

      - name: "Build and push QMD container"
        uses: synpulse-group/s8-actions/custom-build-push-container@main
        with:
          docker-build-context-location: ./docker/qmd
          docker-file-path: ./docker/qmd/Dockerfile.gpu
          jfrog-user: ${{ secrets.JFROG_USER_PULSE8_AI }}
          jfrog-password: ${{ secrets.JFROG_ACCESS_TOKEN_PULSE8_AI }}
          image-name-suffix: -cortex-vault-qmd-test
          target-repository: "sp-artifactory-dso-internal-pulse8-ai"
